language: python
python:
  - "3.6"
# command to install dependencies
env:
 +  - PYTHON_VERSION=3.6 MAKE_DOC=TRUE
    - PYTHON_VERSION=3.5 MAKE_DOC=TRUE
    - PYTHON_VERSION=3.4 USE_CYTHON=TRUE
  before_install:
 @@ -15,9 +16,12 @@ before_install:
    # Update conda itself
    - conda update --yes conda
  install:
 -  - conda create --yes -n env_name python=$PYTHON_VERSION --file ci/conda_requirements.txt
 +  - conda create --yes -n env_name python=$PYTHON_VERSION
 +  - conda install --yes -n env_name --file ci/conda_requirements.txt
    - if [ ${USE_CYTHON} ]; then conda install --yes -n env_name cython; fi
    - source activate env_name
 +  - conda info --envs
 +  - python --version
    - pip install -r ci/pip_requirements.txt
    - pip install . --no-deps
script:
  - pytest # or py.test for Python versions 3.5 and below
 
